# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enn3/uni/arch/progetto5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enn3/uni/arch/progetto5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enn3/uni/arch/progetto5/CMakeFiles /home/enn3/uni/arch/progetto5//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enn3/uni/arch/progetto5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named progetto5

# Build rule for target.
progetto5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 progetto5
.PHONY : progetto5

# fast build rule for target.
progetto5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/build
.PHONY : progetto5/fast

assembler.o: assembler.c.o
.PHONY : assembler.o

# target to build an object file
assembler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/assembler.c.o
.PHONY : assembler.c.o

assembler.i: assembler.c.i
.PHONY : assembler.i

# target to preprocess a source file
assembler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/assembler.c.i
.PHONY : assembler.c.i

assembler.s: assembler.c.s
.PHONY : assembler.s

# target to generate assembly for a file
assembler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/assembler.c.s
.PHONY : assembler.c.s

file.o: file.c.o
.PHONY : file.o

# target to build an object file
file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/file.c.o
.PHONY : file.c.o

file.i: file.c.i
.PHONY : file.i

# target to preprocess a source file
file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/file.c.i
.PHONY : file.c.i

file.s: file.c.s
.PHONY : file.s

# target to generate assembly for a file
file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/file.c.s
.PHONY : file.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/main.c.s
.PHONY : main.c.s

preproccesor.o: preproccesor.c.o
.PHONY : preproccesor.o

# target to build an object file
preproccesor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/preproccesor.c.o
.PHONY : preproccesor.c.o

preproccesor.i: preproccesor.c.i
.PHONY : preproccesor.i

# target to preprocess a source file
preproccesor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/preproccesor.c.i
.PHONY : preproccesor.c.i

preproccesor.s: preproccesor.c.s
.PHONY : preproccesor.s

# target to generate assembly for a file
preproccesor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/preproccesor.c.s
.PHONY : preproccesor.c.s

string.o: string.c.o
.PHONY : string.o

# target to build an object file
string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/string.c.o
.PHONY : string.c.o

string.i: string.c.i
.PHONY : string.i

# target to preprocess a source file
string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/string.c.i
.PHONY : string.c.i

string.s: string.c.s
.PHONY : string.s

# target to generate assembly for a file
string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/string.c.s
.PHONY : string.c.s

variables.o: variables.c.o
.PHONY : variables.o

# target to build an object file
variables.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/variables.c.o
.PHONY : variables.c.o

variables.i: variables.c.i
.PHONY : variables.i

# target to preprocess a source file
variables.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/variables.c.i
.PHONY : variables.c.i

variables.s: variables.c.s
.PHONY : variables.s

# target to generate assembly for a file
variables.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/progetto5.dir/build.make CMakeFiles/progetto5.dir/variables.c.s
.PHONY : variables.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... progetto5"
	@echo "... assembler.o"
	@echo "... assembler.i"
	@echo "... assembler.s"
	@echo "... file.o"
	@echo "... file.i"
	@echo "... file.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... preproccesor.o"
	@echo "... preproccesor.i"
	@echo "... preproccesor.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
	@echo "... variables.o"
	@echo "... variables.i"
	@echo "... variables.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

